pub mod insert_in_database;
pub mod modules; // Add crate attribute to enable unstable library feature 'test'

#[cfg(test)]

mod tests {
    use crate::modules::json::structs::dest::Dest;
    use crate::modules::json::structs::emit::Emit;
    use crate::modules::json::structs::ender::Ender;
    use crate::modules::json::structs::impostos::*;
    use crate::modules::json::structs::nfe::Nfe;
    use crate::modules::json::structs::produtos::Produto;

    #[test]
    fn read_folder() {
        let input = crate::modules::util::read_folder::list_folder("tests/data")
            .expect("Error reading folder");
        let expected: Vec<String> = vec![
            "tests/data/1.xml".to_string(),
            "tests/data/2.xml".to_string(),
        ];
        assert_eq!(input, expected);
    }

    #[test]
    fn new_nfe_vec_products() {
        let input = Nfe::new("tests/data/1.xml");
        let expected = Nfe {
            nfe_cdv: "3".to_string(),
            nfe_cmunfg: "3304557".to_string(),
            nfe_cnf: "00151204".to_string(),
            nfe_cuf: "33".to_string(),
            nfe_dhemi: "2023-12-11T19:55:57-03:00".to_string(),
            nfe_dhsaient: "2023-12-11T19:55:57-03:00".to_string(),
            nfe_finnfe: "1".to_string(),
            nfe_nfe_iddest: "2".to_string(),
            nfe_indfinal: "1".to_string(),
            nfe_indintermed: "0".to_string(),
            nfe_indpres: "2".to_string(),
            nfe_modnfe: "55".to_string(),
            nfe_nnf: "00000000001".to_string(),
            nfe_natop: "NOTA DE TESTE".to_string(),
            nfe_procemi: "0".to_string(),
            nfe_serie: "4".to_string(),
            nfe_tpamb: "1".to_string(),
            nfe_tpemis: "1".to_string(),
            nfe_tpimp: "1".to_string(),
            nfe_tpnf: "1".to_string(),
            nfe_verproc: "Notamax 1.0".to_string(),
            nfe_nftotal: 149.70,
            nfe_emit: Emit {
                emit_cnpjcpf: "99999999999999".to_string(),
                emit_crt: "3".to_string(),
                emit_ie: "86607492".to_string(),
                emit_iest: "819012855115".to_string(),
                ender_emit: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "RJ".to_string(),
                    ender_cmun: "3304557".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "9999".to_string(),
                    ender_xbairro: "BAIRRO DA LOJA TEST".to_string(),
                    ender_xcpl: "Compemento".to_string(),
                    ender_xlgr: "RUA DA LOJA TEST".to_string(),
                    ender_xmun: "Rio de Janeiro".to_string(),
                },
                emit_xfant: "LOJA DE TESTE".to_string(),
                emit_xnome: "LOJA DE TESTE".to_string(),
            },
            nfe_dest: Dest {
                dest_cnpjcpf: "99999999999".to_string(),
                dest_ie: "null".to_string(),
                dest_email: "email@test.com".to_string(),
                dest_ender: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "SP".to_string(),
                    ender_cmun: "99999999".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "31".to_string(),
                    ender_xbairro: "BAIRRO DO CLIENTE PF DE TESTE".to_string(),
                    ender_xcpl: "null".to_string(),
                    ender_xlgr: "RUA DO CLIENTE PF DE TESTE".to_string(),
                    ender_xmun: "Catanduva".to_string(),
                },
                dest_indiedest: "9".to_string(),
                dest_xnome: "CLIENTE PF DE TESTE".to_string(),
            },
            nfe_produtos: vec![
                Produto {
                    produto_nitem: "1".to_string(),
                    produto_cprod: "678651245".to_string(),
                    produto_cean: "SEM GTIN".to_string(),
                    produto_xprod: "CAMISETA MANGA CURTA ALGODAO".to_string(),
                    produto_ncm: "61091000".to_string(),
                    produto_cfop: "6108".to_string(),
                    produto_ucom: "UN".to_string(),
                    produto_qcom: 1.0,
                    produto_vuncom: 69.9,
                    produto_vprod: 69.9,
                    produto_ceantrib: "SEM GTIN".to_string(),
                    produto_utrib: "UN".to_string(),
                    produto_qtrib: 1.0,
                    produto_vuntrib: 69.9,
                    produto_indtot: "1".to_string(),
                    produto_xped: "999999999".to_string(),
                    imposto: Imposto {
                        imposto_icms: Icms {
                            icms_orig: 0,
                            icms_cst: 0,
                            icms_modbc: 3,
                            icms_vbc: 69.9,
                            icms_picms: 12.0,
                            icms_vicms: 8.39,
                        },
                        imposto_ipi: Ipi {
                            ipi_cenq: 0,
                            ipi_cst: 0,
                            ipi_vbc: 0.0,
                            ipi_pipi: 0,
                            ipi_vipi: 0,
                        },
                        imposto_pis: Pis {
                            pis_cst: 1,
                            pis_vbc: 57.32,
                            pis_ppis: 1.65,
                            pis_vpis: 0.95,
                        },
                        imposto_cofins: Cofins {
                            cofins_cst: 1,
                            cofins_vbc: 57.32,
                            cofins_pcofins: 7.6,
                            cofins_vcofins: 4.36,
                        },
                        imposto_icms_uf_dest: IcmsUfDest {
                            icms_uf_vbcufdest: 69.9,
                            icms_uf_vbcfcpufdest: 69.9,
                            icms_uf_pfcpufdest: 0.0,
                            icms_uf_picmsufdest: 18.0,
                            icms_uf_picmsinter: 12.0,
                            icms_uf_picmsinterpart: 100.0,
                            icms_uf_vfcpufdest: 0.0,
                            icms_uf_vicmsufdest: 4.19,
                            icms_uf_vicmsufremet: 0.0,
                        },
                    },
                },
                Produto {
                    produto_nitem: "2".to_string(),
                    produto_cprod: "742245576".to_string(),
                    produto_cean: "SEM GTIN".to_string(),
                    produto_xprod: "CAMISETA MANGA CURTA ALGODAO GEOMETRICO".to_string(),
                    produto_ncm: "61091000".to_string(),
                    produto_cfop: "6108".to_string(),
                    produto_ucom: "UN".to_string(),
                    produto_qcom: 1.0,
                    produto_vuncom: 29.9,
                    produto_vprod: 29.9,
                    produto_ceantrib: "SEM GTIN".to_string(),
                    produto_utrib: "UN".to_string(),
                    produto_qtrib: 1.0,
                    produto_vuntrib: 29.9,
                    produto_indtot: "1".to_string(),
                    produto_xped: "999999999".to_string(),
                    imposto: Imposto {
                        imposto_icms: Icms {
                            icms_orig: 0,
                            icms_cst: 0,
                            icms_modbc: 3,
                            icms_vbc: 29.9,
                            icms_picms: 12.0,
                            icms_vicms: 3.59,
                        },
                        imposto_ipi: Ipi {
                            ipi_cenq: 0,
                            ipi_cst: 0,
                            ipi_vbc: 0.0,
                            ipi_pipi: 0,
                            ipi_vipi: 0,
                        },
                        imposto_pis: Pis {
                            pis_cst: 1,
                            pis_vbc: 24.52,
                            pis_ppis: 1.65,
                            pis_vpis: 0.4,
                        },
                        imposto_cofins: Cofins {
                            cofins_cst: 1,
                            cofins_vbc: 24.52,
                            cofins_pcofins: 7.6,
                            cofins_vcofins: 1.86,
                        },
                        imposto_icms_uf_dest: IcmsUfDest {
                            icms_uf_vbcufdest: 29.9,
                            icms_uf_vbcfcpufdest: 29.9,
                            icms_uf_pfcpufdest: 0.0,
                            icms_uf_picmsufdest: 18.0,
                            icms_uf_picmsinter: 12.0,
                            icms_uf_picmsinterpart: 100.0,
                            icms_uf_vfcpufdest: 0.0,
                            icms_uf_vicmsufdest: 1.79,
                            icms_uf_vicmsufremet: 0.0,
                        },
                    },
                },
                Produto {
                    produto_nitem: "3".to_string(),
                    produto_cprod: "882668327".to_string(),
                    produto_cean: "SEM GTIN".to_string(),
                    produto_xprod: "CAMISETA MANGA CURTA MEIA MALHA".to_string(),
                    produto_ncm: "61091000".to_string(),
                    produto_cfop: "6108".to_string(),
                    produto_ucom: "UN".to_string(),
                    produto_qcom: 1.0,
                    produto_vuncom: 49.9,
                    produto_vprod: 49.9,
                    produto_ceantrib: "SEM GTIN".to_string(),
                    produto_utrib: "UN".to_string(),
                    produto_qtrib: 1.0,
                    produto_vuntrib: 49.9,
                    produto_indtot: "1".to_string(),
                    produto_xped: "999999999".to_string(),
                    imposto: Imposto {
                        imposto_icms: Icms {
                            icms_orig: 0,
                            icms_cst: 0,
                            icms_modbc: 3,
                            icms_vbc: 49.9,
                            icms_picms: 12.0,
                            icms_vicms: 5.99,
                        },
                        imposto_ipi: Ipi {
                            ipi_cenq: 0,
                            ipi_cst: 0,
                            ipi_vbc: 0.0,
                            ipi_pipi: 0,
                            ipi_vipi: 0,
                        },
                        imposto_pis: Pis {
                            pis_cst: 1,
                            pis_vbc: 40.92,
                            pis_ppis: 1.65,
                            pis_vpis: 0.68,
                        },
                        imposto_cofins: Cofins {
                            cofins_cst: 1,
                            cofins_vbc: 40.92,
                            cofins_pcofins: 7.6,
                            cofins_vcofins: 3.11,
                        },
                        imposto_icms_uf_dest: IcmsUfDest {
                            icms_uf_vbcufdest: 49.9,
                            icms_uf_vbcfcpufdest: 49.9,
                            icms_uf_pfcpufdest: 0.0,
                            icms_uf_picmsufdest: 18.0,
                            icms_uf_picmsinter: 12.0,
                            icms_uf_picmsinterpart: 100.0,
                            icms_uf_vfcpufdest: 0.0,
                            icms_uf_vicmsufdest: 2.99,
                            icms_uf_vicmsufremet: 0.0,
                        },
                    },
                },
            ],
        };
        assert_eq!(input, expected);
    }

    #[test]
    fn new_nfe_single_products() {
        let input = Nfe::new("tests/data/2.xml");
        let expected = Nfe {
            nfe_cdv: "3".to_string(),
            nfe_cmunfg: "3304557".to_string(),
            nfe_cnf: "00151204".to_string(),
            nfe_cuf: "33".to_string(),
            nfe_dhemi: "2023-12-11T19:55:57-03:00".to_string(),
            nfe_dhsaient: "2023-12-11T19:55:57-03:00".to_string(),
            nfe_finnfe: "1".to_string(),
            nfe_nfe_iddest: "2".to_string(),
            nfe_indfinal: "1".to_string(),
            nfe_indintermed: "0".to_string(),
            nfe_indpres: "2".to_string(),
            nfe_modnfe: "55".to_string(),
            nfe_nnf: "00000000002".to_string(),
            nfe_natop: "NOTA DE TESTE".to_string(),
            nfe_procemi: "0".to_string(),
            nfe_serie: "4".to_string(),
            nfe_tpamb: "1".to_string(),
            nfe_tpemis: "1".to_string(),
            nfe_tpimp: "1".to_string(),
            nfe_tpnf: "1".to_string(),
            nfe_verproc: "Notamax 1.0".to_string(),
            nfe_nftotal: 74.99,
            nfe_emit: Emit {
                emit_cnpjcpf: "99999999999999".to_string(),
                emit_crt: "3".to_string(),
                emit_ie: "86607492".to_string(),
                emit_iest: "819012855115".to_string(),
                ender_emit: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "RJ".to_string(),
                    ender_cmun: "3304557".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "9999".to_string(),
                    ender_xbairro: "BAIRRO DA LOJA TEST".to_string(),
                    ender_xcpl: "Compemento".to_string(),
                    ender_xlgr: "RUA DA LOJA TEST".to_string(),
                    ender_xmun: "Rio de Janeiro".to_string(),
                },
                emit_xfant: "LOJA DE TESTE".to_string(),
                emit_xnome: "LOJA DE TESTE".to_string(),
            },
            nfe_dest: Dest {
                dest_cnpjcpf: "99999999999".to_string(),
                dest_ie: "null".to_string(),
                dest_email: "email@test.com".to_string(),
                dest_ender: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "SP".to_string(),
                    ender_cmun: "99999999".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "31".to_string(),
                    ender_xbairro: "BAIRRO DO CLIENTE PF DE TESTE".to_string(),
                    ender_xcpl: "null".to_string(),
                    ender_xlgr: "RUA DO CLIENTE PF DE TESTE".to_string(),
                    ender_xmun: "Catanduva".to_string(),
                },
                dest_indiedest: "9".to_string(),
                dest_xnome: "CLIENTE PF DE TESTE".to_string(),
            },
            nfe_produtos: vec![Produto {
                produto_nitem: "1".to_string(),
                produto_cprod: "000I0020NUD000M".to_string(),
                produto_cean: "7899625704614".to_string(),
                produto_xprod: "ROUPA DE ALGODAO".to_string(),
                produto_ncm: "62121000".to_string(),
                produto_cfop: "6102".to_string(),
                produto_ucom: "UN".to_string(),
                produto_qcom: 10.0,
                produto_vuncom: 61.43,
                produto_vprod: 614.3,
                produto_ceantrib: "7899625704614".to_string(),
                produto_utrib: "UN".to_string(),
                produto_qtrib: 10.0,
                produto_vuntrib: 61.43,
                produto_indtot: "1".to_string(),
                produto_xped: "null".to_string(),
                imposto: Imposto {
                    imposto_icms: Icms {
                        icms_orig: 1,
                        icms_cst: 0,
                        icms_modbc: 3,
                        icms_vbc: 583.59,
                        icms_picms: 4.0,
                        icms_vicms: 23.34,
                    },
                    imposto_ipi: Ipi {
                        ipi_cenq: 999,
                        ipi_cst: 50,
                        ipi_vbc: 614.30,
                        ipi_pipi: 0,
                        ipi_vipi: 0,
                    },
                    imposto_pis: Pis {
                        pis_cst: 1,
                        pis_vbc: 560.25,
                        pis_ppis: 1.65,
                        pis_vpis: 9.24,
                    },
                    imposto_cofins: Cofins {
                        cofins_cst: 1,
                        cofins_vbc: 560.25,
                        cofins_pcofins: 7.6,
                        cofins_vcofins: 42.58,
                    },
                    imposto_icms_uf_dest: IcmsUfDest {
                        icms_uf_vbcufdest: 0.0,
                        icms_uf_vbcfcpufdest: 0.0,
                        icms_uf_pfcpufdest: 0.0,
                        icms_uf_picmsufdest: 0.0,
                        icms_uf_picmsinter: 0.0,
                        icms_uf_picmsinterpart: 0.0,
                        icms_uf_vfcpufdest: 0.0,
                        icms_uf_vicmsufdest: 0.0,
                        icms_uf_vicmsufremet: 0.0,
                    },
                },
            }],
        };
        assert_eq!(input, expected);
    }
}
