pub mod insert_in_database;
pub mod modules; // Add crate attribute to enable unstable library feature 'test'

#[cfg(test)]

mod tests {
    use crate::modules::json::structs::dest::Dest;
    use crate::modules::json::structs::emit::Emit;
    use crate::modules::json::structs::ender::Ender;
    use crate::modules::json::structs::impostos::*;
    use crate::modules::json::structs::nfe::Nfe;
    use crate::modules::json::structs::produtos::Produto;

    #[test]
    fn read_folder() {
        let input = crate::modules::util::read_folder::list_folder("tests/data")
            .expect("Error reading folder");
        let expected: Vec<String> = vec![
            "tests/data/1.xml".to_string(),
            "tests/data/2.xml".to_string(),
        ];
        assert_eq!(input, expected);
    }

    #[test]
    fn new_nfe_vec_products() {
        let input = Nfe::new("tests/data/1.xml");
        let expected = Nfe {
            c_dv: "3".to_string(),
            c_mun_fg: "3304557".to_string(),
            c_nf: "00151204".to_string(),
            c_uf: "33".to_string(),
            dh_emi: "2023-12-11T19:55:57-03:00".to_string(),
            dh_sai_ent: "2023-12-11T19:55:57-03:00".to_string(),
            fin_nfe: "1".to_string(),
            id_dest: "2".to_string(),
            ind_final: "1".to_string(),
            ind_intermed: "0".to_string(),
            ind_pres: "2".to_string(),
            mod_nfe: "55".to_string(),
            n_nf: "00000000001".to_string(),
            nat_op: "NOTA DE TESTE".to_string(),
            proc_emi: "0".to_string(),
            serie: "4".to_string(),
            tp_amb: "1".to_string(),
            tp_emis: "1".to_string(),
            tp_imp: "1".to_string(),
            tp_nf: "1".to_string(),
            ver_proc: "Notamax 1.0".to_string(),
            nf_total: 149.70,
            emit: Emit {
                emit_cnpjcpf: "99999999999999".to_string(),
                emit_crt: "3".to_string(),
                emit_ie: "86607492".to_string(),
                emit_iest: "819012855115".to_string(),
                ender_emit: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "RJ".to_string(),
                    ender_cmun: "3304557".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "9999".to_string(),
                    ender_xbairro: "BAIRRO DA LOJA TEST".to_string(),
                    ender_xcpl: "Compemento".to_string(),
                    ender_xlgr: "RUA DA LOJA TEST".to_string(),
                    ender_xmun: "Rio de Janeiro".to_string(),
                },
                emit_xfant: "LOJA DE TESTE".to_string(),
                emit_xnome: "LOJA DE TESTE".to_string(),
            },
            dest: Dest {
                dest_cnpjcpf: "99999999999".to_string(),
                dest_ie: "null".to_string(),
                dest_email: "email@test.com".to_string(),
                dest_ender: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "SP".to_string(),
                    ender_cmun: "99999999".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "31".to_string(),
                    ender_xbairro: "BAIRRO DO CLIENTE PF DE TESTE".to_string(),
                    ender_xcpl: "null".to_string(),
                    ender_xlgr: "RUA DO CLIENTE PF DE TESTE".to_string(),
                    ender_xmun: "Catanduva".to_string(),
                },
                dest_indiedest: "9".to_string(),
                dest_xnome: "CLIENTE PF DE TESTE".to_string(),
            },
            produtos: vec![
                Produto {
                    n_item: "1".to_string(),
                    c_prod: "678651245".to_string(),
                    c_ean: "SEM GTIN".to_string(),
                    x_prod: "CAMISETA MANGA CURTA ALGODAO".to_string(),
                    ncm: "61091000".to_string(),
                    cfop: "6108".to_string(),
                    u_com: "UN".to_string(),
                    q_com: 1.0,
                    v_un_com: 69.9,
                    v_prod: 69.9,
                    c_eantrib: "SEM GTIN".to_string(),
                    u_trib: "UN".to_string(),
                    q_trib: 1.0,
                    v_un_trib: 69.9,
                    ind_tot: "1".to_string(),
                    x_ped: "999999999".to_string(),
                    impostos: Impostos {
                        icms: Icms {
                            icms_orig: 0,
                            icms_cst: 0,
                            icms_modbc: 3,
                            icms_vbc: 69.9,
                            icms_picms: 12.0,
                            icms_vicms: 8.39,
                        },
                        ipi: Ipi {
                            ipi_cenq: 0,
                            ipi_cst: 0,
                            ipi_vbc: 0.0,
                            ipi_pipi: 0,
                            ipi_vipi: 0,
                        },
                        pis: Pis {
                            pis_cst: 1,
                            pis_vbc: 57.32,
                            pis_ppis: 1.65,
                            pis_vpis: 0.95,
                        },
                                cofins: Cofins {
                                    cofins_cst: 1,
                                    cofins_vbc: 57.32,
                                    cofins_pcofins: 7.6,
                                    cofins_vcofins: 4.36,
                                },
                                icms_uf_dest: IcmsUfDest {
                                    icms_uf_vbcufdest: 69.9,
                                    icms_uf_vbcfcpufdest: 69.9,
                                    icms_uf_pfcpufdest: 0.0,
                                    icms_uf_picmsufdest: 18.0,
                                    icms_uf_picmsinter: 12.0,
                                    icms_uf_picmsinterpart: 100.0,
                                    icms_uf_vfcpufdest: 0.0,
                                    icms_uf_vicmsufdest: 4.19,
                                    icms_uf_vicmsufremet: 0.0,
                                },
                            },
                        },
                        Produto {
                            n_item: "2".to_string(),
                            c_prod: "742245576".to_string(),
                            c_ean: "SEM GTIN".to_string(),
                            x_prod: "CAMISETA MANGA CURTA ALGODAO GEOMETRICO".to_string(),
                            ncm: "61091000".to_string(),
                            cfop: "6108".to_string(),
                            u_com: "UN".to_string(),
                            q_com: 1.0,
                            v_un_com: 29.9,
                            v_prod: 29.9,
                            c_eantrib: "SEM GTIN".to_string(),
                            u_trib: "UN".to_string(),
                            q_trib: 1.0,
                            v_un_trib: 29.9,
                            ind_tot: "1".to_string(),
                            x_ped: "999999999".to_string(),
                            impostos: Impostos {
                                icms: Icms {
                                    icms_orig: 0,
                                    icms_cst: 0,
                                    icms_modbc: 3,
                                    icms_vbc: 29.9,
                                    icms_picms: 12.0,
                                    icms_vicms: 3.59,
                                },
                                ipi: Ipi {
                                    ipi_cenq: 0,
                                    ipi_cst: 0,
                                    ipi_vbc: 0.0,
                                    ipi_pipi: 0,
                                    ipi_vipi: 0,
                                },
                                pis: Pis {
                                    pis_cst: 1,
                                    pis_vbc: 24.52,
                                    pis_ppis: 1.65,
                                    pis_vpis: 0.4,
                                },
                                cofins: Cofins {
                                    cofins_cst: 1,
                                    cofins_vbc: 24.52,
                                    cofins_pcofins: 7.6,
                                    cofins_vcofins: 1.86,
                                },
                                icms_uf_dest: IcmsUfDest {
                                    icms_uf_vbcufdest: 29.9,
                                    icms_uf_vbcfcpufdest: 29.9,
                                    icms_uf_pfcpufdest: 0.0,
                                    icms_uf_picmsufdest: 18.0,
                                    icms_uf_picmsinter: 12.0,
                                    icms_uf_picmsinterpart: 100.0,
                                    icms_uf_vfcpufdest: 0.0,
                                    icms_uf_vicmsufdest: 1.79,
                                    icms_uf_vicmsufremet: 0.0,
                                },
                            },
                        },
                        Produto {
                            n_item: "3".to_string(),
                            c_prod: "882668327".to_string(),
                            c_ean: "SEM GTIN".to_string(),
                            x_prod: "CAMISETA MANGA CURTA MEIA MALHA".to_string(),
                            ncm: "61091000".to_string(),
                            cfop: "6108".to_string(),
                            u_com: "UN".to_string(),
                            q_com: 1.0,
                            v_un_com: 49.9,
                            v_prod: 49.9,
                            c_eantrib: "SEM GTIN".to_string(),
                            u_trib: "UN".to_string(),
                            q_trib: 1.0,
                            v_un_trib: 49.9,
                            ind_tot: "1".to_string(),
                            x_ped: "999999999".to_string(),
                            impostos: Impostos {
                                icms: Icms {
                                    icms_orig: 0,
                                    icms_cst: 0,
                                    icms_modbc: 3,
                                    icms_vbc: 49.9,
                                    icms_picms: 12.0,
                                    icms_vicms: 5.99,
                                },
                                ipi: Ipi {
                                    ipi_cenq: 0,
                                    ipi_cst: 0,
                                    ipi_vbc: 0.0,
                                    ipi_pipi: 0,
                                    ipi_vipi: 0,
                                },
                                pis: Pis {
                                    pis_cst: 1,
                                    pis_vbc: 40.92,
                                    pis_ppis: 1.65,
                                    pis_vpis: 0.68,
                                },
                                cofins: Cofins {
                                    cofins_cst: 1,
                                    cofins_vbc: 40.92,
                                    cofins_pcofins: 7.6,
                                    cofins_vcofins: 3.11,
                        },
                        icms_uf_dest: IcmsUfDest {
                            icms_uf_vbcufdest: 49.9,
                            icms_uf_vbcfcpufdest: 49.9,
                            icms_uf_pfcpufdest: 0.0,
                            icms_uf_picmsufdest: 18.0,
                            icms_uf_picmsinter: 12.0,
                            icms_uf_picmsinterpart: 100.0,
                            icms_uf_vfcpufdest: 0.0,
                            icms_uf_vicmsufdest: 2.99,
                            icms_uf_vicmsufremet: 0.0,
                        },
                    },
                },
            ],
        };
        assert_eq!(input, expected);
    }

    #[test]
    fn new_nfe_single_products() {
        let input = Nfe::new("tests/data/2.xml");
        let expected = Nfe {
            c_dv: "3".to_string(),
            c_mun_fg: "3304557".to_string(),
            c_nf: "00151204".to_string(),
            c_uf: "33".to_string(),
            dh_emi: "2023-12-11T19:55:57-03:00".to_string(),
            dh_sai_ent: "2023-12-11T19:55:57-03:00".to_string(),
            fin_nfe: "1".to_string(),
            id_dest: "2".to_string(),
            ind_final: "1".to_string(),
            ind_intermed: "0".to_string(),
            ind_pres: "2".to_string(),
            mod_nfe: "55".to_string(),
            n_nf: "00000000002".to_string(),
            nat_op: "NOTA DE TESTE".to_string(),
            proc_emi: "0".to_string(),
            serie: "4".to_string(),
            tp_amb: "1".to_string(),
            tp_emis: "1".to_string(),
            tp_imp: "1".to_string(),
            tp_nf: "1".to_string(),
            ver_proc: "Notamax 1.0".to_string(),
            nf_total: 74.99,
            emit: Emit {
                emit_cnpjcpf: "99999999999999".to_string(),
                emit_crt: "3".to_string(),
                emit_ie: "86607492".to_string(),
                emit_iest: "819012855115".to_string(),
                ender_emit: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "RJ".to_string(),
                    ender_cmun: "3304557".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "9999".to_string(),
                    ender_xbairro: "BAIRRO DA LOJA TEST".to_string(),
                    ender_xcpl: "Compemento".to_string(),
                    ender_xlgr: "RUA DA LOJA TEST".to_string(),
                    ender_xmun: "Rio de Janeiro".to_string(),
                },
                emit_xfant: "LOJA DE TESTE".to_string(),
                emit_xnome: "LOJA DE TESTE".to_string(),
            },
            dest: Dest {
                dest_cnpjcpf: "99999999999".to_string(),
                dest_ie: "null".to_string(),
                dest_email: "email@test.com".to_string(),
                dest_ender: Ender {
                    ender_cep: "9999999".to_string(),
                    ender_uf: "SP".to_string(),
                    ender_cmun: "99999999".to_string(),
                    ender_cpais: "1058".to_string(),
                    ender_nro: "31".to_string(),
                    ender_xbairro: "BAIRRO DO CLIENTE PF DE TESTE".to_string(),
                    ender_xcpl: "null".to_string(),
                    ender_xlgr: "RUA DO CLIENTE PF DE TESTE".to_string(),
                    ender_xmun: "Catanduva".to_string(),
                },
                dest_indiedest: "9".to_string(),
                dest_xnome: "CLIENTE PF DE TESTE".to_string(),
            },
            produtos: vec![Produto {
                n_item: "1".to_string(),
                c_prod: "000I0020NUD000M".to_string(),
                c_ean: "7899625704614".to_string(),
                x_prod: "ROUPA DE ALGUDAO".to_string(),
                ncm: "62121000".to_string(),
                cfop: "6102".to_string(),
                u_com: "UN".to_string(),
                q_com: 10.0,
                v_un_com: 61.43,
                v_prod: 614.3,
                c_eantrib: "7899625704614".to_string(),
                u_trib: "UN".to_string(),
                q_trib: 10.0,
                v_un_trib: 61.43,
                ind_tot: "1".to_string(),
                x_ped: "null".to_string(),
                impostos: Impostos {
                    icms: Icms {
                        icms_orig: 1,
                        icms_cst: 0,
                        icms_modbc: 3,
                        icms_vbc: 583.59,
                        icms_picms: 4.0,
                        icms_vicms: 23.34,
                    },
                    ipi: Ipi {
                        ipi_cenq: 999,
                        ipi_cst: 50,
                        ipi_vbc: 614.30,
                        ipi_pipi: 0,
                        ipi_vipi: 0,
                    },
                    pis: Pis {
                        pis_cst: 1,
                        pis_vbc: 560.25,
                        pis_ppis: 1.65,
                        pis_vpis: 9.24,
                    },
                    cofins: Cofins {
                        cofins_cst: 1,
                        cofins_vbc: 560.25,
                        cofins_pcofins: 7.6,
                        cofins_vcofins: 42.58,
                    },
                    icms_uf_dest: IcmsUfDest {
                        icms_uf_vbcufdest: 0.0,
                        icms_uf_vbcfcpufdest: 0.0,
                        icms_uf_pfcpufdest: 0.0,
                        icms_uf_picmsufdest: 0.0,
                        icms_uf_picmsinter: 0.0,
                        icms_uf_picmsinterpart: 0.0,
                        icms_uf_vfcpufdest: 0.0,
                        icms_uf_vicmsufdest: 0.0,
                        icms_uf_vicmsufremet: 0.0,
                    },
                },
            }],
        };
        assert_eq!(input, expected);
    }
}
