use super::{emit::Emit, dest::Dest, produtos::Produto};

pub struct Nfe {
    pub c_dv: i64,
    pub c_mun_fg: i64,
    pub c_nf: i64,
    pub c_uf: i64,
    pub dh_emi: String,
    pub dh_sai_ent: String,
    pub fin_nfe: i32,
    pub id_dest: i32,
    pub ind_final: i32,
    pub ind_intermed: i32,
    pub ind_pres: i32,
    pub mod_nfe: i32,
    pub n_nf: i64,
    pub nat_op: String,
    pub proc_emi: i32,
    pub serie: i32,
    pub tp_amb: i32,
    pub tp_emis: i32,
    pub tp_imp: i32,
    pub tp_nf: i32,
    pub ver_proc: String,
    pub emit: Emit,
    pub dest: Dest,
    pub produtos: Vec<Produto>,
}