[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
axum = { version = "0.7.2", features = ["multipart"]}
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
dotenv = "0.15.0"
tower-http = {version = "0.5.0", features = ["cors"]}
uuid = { version = "1.6.1", features = ["v4"] }
chrono = "0.4.31"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio-rustls", "uuid"] }


nfe = { path = "../nfe" }
jsonwebtoken = "9.2.0"
lazy_static = "1.4.0"
