[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
uuid = { version = "1.8.0", features = ["serde","v4"] }
sqlx = { version = "0.7.4", features = ["uuid", "time", "chrono", "bigdecimal"] }
